export default [
  'Otro',
  'Rotaract Club Ayacucho',
  'Rotaract Puerto Mar del Plata',
  'Rotaract Club Villa Gesell',
  'Rotaract Club Del Mar EF',
  'Rotaract Club Bolivar',
  'Rotaract Club Dolores EF',
  'Rotaract Club Tandil',
  'Rotaract Club Santa Teresita EF',
  'Rotaract Olavarría Norte',
  'Rotaract Club Santiago del Estero',
  'Rotaract Club General Pico',
  'Rotaract Club Santa Rosa',
  'Rotaract Club Trenque Lauquen',
  'Rotaract Club Bahía Blanca Almafuerte',
  'Rotaract Club Tres Arroyos Libertad',
  'Rotaract Club Punta Alta',
  'Rotaract Club Coronel Pringles',
  'Rotaract Club Allen',
  'Rotaract Club Cipolletti Comahue',
  'Rotaract Club Cinco Saltos',
  'Rotaract Club Villa Regina',
  'Rotaract Club Bariloche Nuevas Generaciones',
  'Rotaract Club Esquel',
  'Rotaract Club Comodoro Rivadavia',
  'Rotaract Club Ushuaia EF',
  'Rotaract Club Oberá (En formación)',
  'Rotaract Club Resistencia Oeste',
  'Rotaract Club Posadas',
  'Rotaract Club Paso de los Libres San José',
  'Rotaract Club Posadas Norte',
  'Rotaract Club Asunción',
  'Rotaract Club Ciudad del Este',
  'Rotaract Club Saenz Peña Gualok',
  'Rotaract Club Aristóbulo del Valle',
  'Rotaract Club Asuncion Catedral',
  'Rotaract Club San Luis del Palmar',
  'Rotaract Club Posadas Oeste',
  'Rotaract Club Mercedes',
  'Rotaract Club Sáenz Peña',
  'Rotaract Club Formosa',
  'Rotaract Club Encarnacion Norte',
  'Rotaract Club Curuzu Cuatiá',
  'Rotaract Club Santo Tomé',
  'Rotaract Club Río Paraná Corrientes',
  'Rotaract Club Trinidad Asunción',
  'Rotaract Club Formosa 8 de Abril',
  'Rotaract Club Lambaré Costa del Río',
  'Rotaract Club Encarnación Oeste',
  'Rotaract Club Encarnación',
  'Rotaract Club Concepción',
  'Rotaract Club Villa Morra',
  'Rotaract Club San Lorenzo',
  'Rotaract Club Sin Fronteras',
  'Rotaract Club San Estanislao',
  'Rotaract Club Resistencia Sur',
  'Rotaract Club Paso de los Libres',
  'Rotaract Club Fernando de la Mora',
  'Rotaract Club Clorinda',
  'Rotaract Club Villarrica',
  'Rotaract Club Corrientes Costanera',
  'Rotaract Club Resistencia Centro',
  'Rotaract Club Coronel Oviedo Ajos',
  'Rotaract Club Luque',
  'Rotaract Club Posadas Costanera',
  'Rotaract Club Aguada',
  'Rotaract Club Colonia',
  'Rotaract Club Ecildapaullier',
  'Rotaract Club Empalmeolmos',
  'Rotaract Club La Paz',
  'Rotaract Club Montevideo',
  'Rotaract Club Puerto De Buseo',
  'Rotaract Club Piriapolis',
  'Rotaract Club Rio Branco',
  'Rotaract Club Artigas',
  'Rotaract Club Atahualpa',
  'Rotaract Club Boulevard',
  'Rotaract Club Carmelo',
  'Rotaract Club Ituzaingó Maroñas',
  'Rotaract Club Las Piedras',
  'Rotaract Club Lascano',
  'Rotaract Club Libertad',
  'Rotaract Club Malvín',
  'Rotaract Club Parque Rodó Punta Carretas Pocitos',
  'Rotaract Club Progreso',
  'Rotaract Club Rivera Este',
  'Rotaract Club Rivera Internacional',
  'Rotaract Club Rocha Este',
  'Rotaract Club Tacuarembó',
  'Rotaract Club Tala',
  'Rotaract Club Jose Pedro Varela',
  'Rotaract Club Maldonado Este',
  'Rotaract Club Plaza De La Aviación',
  'Rotaract Club Uruguay',
  'Rotaract Club Maldonado',
  'Rotaract Club Plaza Matriz',
  'Rotaract Club San Gregorio',
  'Rotaract Club San Jose',
  'Rotaract Club Belgrano',
  'Rotaract Club Puerto Madero',
  'Rotaract Club Bajo Belgrano Ef',
  'Rotaract Club Buenos Aires',
  'Rotaract Club Libertador Recoleta',
  'Rotaract Club Junin',
  'Rotaract Club Villa Real Versalles',
  'Rotaract Club San Isidro',
  'Rotaract Club San Nicolas',
  'Rotaract Club Junin Sur',
  'Rotaract Club Flores',
  'Rotaract Club San Antonio De Areco',
  'Rotaract Club Carmen De Areco',
  'Rotaract Club Monserrat Uai',
  'Rotaract Club Torre Ader (En Formación)',
  'Rotaract Club Armstrong',
  'Rotaract Club Casilda',
  'Rotaract Club Esperanza',
  'Rotaract Club Federal',
  'Rotaract Club Firmat',
  'Rotaract Club Fray Bentos',
  'Rotaract Club Gálvez',
  'Rotaract Club María Susana',
  'Rotaract Club Paraná',
  'Rotaract Club Paysandú Puerto',
  'Rotaract Club Rafaela',
  'Rotaract Club Rafaela Oeste',
  'Rotaract Club Rosario',
  'Rotaract Club Rosario Plaza de la Bandera',
  'Rotaract Club Rosario Sud',
  'Rotaract Club Rufino',
  'Rotaract Club Salto',
  'Rotaract Club Salto Grande Concordia',
  'Rotaract Club Salto Noreste',
  'Rotaract Club San Justo',
  'Rotaract Club Santa Fe',
  'Rotaract Club Santa Fe Sur',
  'Rotaract Club Sunchales',
  'Rotaract Club Totoras',
  'Rotaract Club Venado Tuerto',
  'Rotaract Club Venado Tuerto Cincuentenario',
  'Rotaract Club Villa Constitución',
  'Rotaract Club San Javier EF',
  'Rotaract Club Rosario Norte EF',
  'Rotaract Club Capitán Bermúdez EF',
  'Rotaract Club Colón EF',
  'Rotaract Club Concepción del Uruguay EF',
  'Rotaract Club Las Parejas EF',
];